DROP TABLE IF EXISTS URL_SHORTENER

CREATE TABLE URL_SHORTENER(
    id INT AUTO_INCREMENT PRIMARY KEY,
    originalURL VARCHAR(250) NOT NULL,
    alias VARCHAR(250) NOT NULL,
    creationDate DATE NOT NULL,
    expiresDate DATE,
);